version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: 8adsfjpiou43952870dsfgjsodfgsp444
        databases:
          default:
            connector: postgres
            host:  ec2-54-225-121-235.compute-1.amazonaws.com
            port: '5432'
            database: d6p3o2r49jg164
            ssl: true
            user: nuaqaogztwcwja
            password: 60ce0aec8821a12be03749e8aa06c12d09ace737ba31a496c6215544e3296ad0
            migrations: true
